package com.dkit.mb;

public enum MenuOptions
{
    CONTINUE,
    Add_STUDENT,
    ADD_BOOKING,
    FIND_AND_EDIT_STUDENT,
    FIND_AND_EDIT_BOOKING,
    PRINT_ALL_STUDENTS,
    PRINT_ALL_BOOKINGS,
    AVERAGE_LENGTH_OF_BOOKINGS,
    PRINT_STATISTICS,
    QUIT;
}
